# Generated by Django 3.1.7 on 2021-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('price', models.FloatField(verbose_name='Стоимость продукта')),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение продукта')),
            ],
        ),
    ]
