# Generated by Django 3.1.7 on 2021-03-06 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Авто комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='asdsadasdasdsa', verbose_name='Текст комментария'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата комментария'),
        ),
    ]
